[package]
name = "yasl-core"
version = "0.1.0"
authors = ["Poly <marynczak.bartlomiej@gmail.com>"]
edition = "2018"


[dependencies]
syn= { version="1.0.18", features=["extra-traits","full"]}
quote="1.0.3"

proc-macro2 = "1.0"